apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-infotrygd-feed
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8092
  liveness:
    path: /internal/status/isAlive
    initialDelay: 20
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 20
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: "1"
    requests:
      memory: 512Mi
      cpu: 200m
  ingresses:
    - https://familie-ef-infotrygd-feed.dev.adeo.no
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak
          namespace: default
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: preprod
