spring:
  datasource:
    url: jdbc:postgresql://b27dbvl015.preprod.local:5432/familie-ef-infotrygd-feed

STS_DISCOVERY_URL: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
AZUREAD_DISCOVERY_URL: https://login.microsoftonline.com/navq.onmicrosoft.com/v2.0/.well-known/openid-configuration
