spring:
  datasource:
    url: jdbc:postgresql://A01DBVL036.adeo.no:5432/familie-ef-infotrygd-feed-15

no.nav.security.jwt:
  issuer.sts:
    discoveryurl: ${STS_DISCOVERY_URL}
    accepted_audience: ${GYLDIG_SERVICE_BRUKER}
  issuer.azuread:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
    accepted_audience: ${AZURE_APP_CLIENT_ID}
    proxyurl: http://webproxy-nais.nav.no:8088

STS_DISCOVERY_URL: https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration
