application:
  name: familie-ef-infotrygd-feed

server:
  servlet:
    context-path: /
  port: 8092

spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main.banner-mode: "off"
  datasource:
    hikari:
      maximum-pool-size: 2
      connection-test-query: "select 1"
      max-lifetime: 30000
      minimum-idle: 1
  data:
    jdbc:
      repositories:
        enabled: true
  flyway:
    enabled: true

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics.export.prometheus.enabled: true
