spring:
  datasource:
    url: jdbc:postgresql://b27dbvl023.preprod.local:5432/familie-ef-infotrygd-feed

STS_DISCOVERY_URL: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
