spring:
  datasource:
    url: jdbc:postgresql://b27dbvl023.preprod.local:5432/familie-ef-infotrygd-feed

no.nav.security.jwt:
  issuer.sts:
    discoveryurl: ${STS_DISCOVERY_URL}
    accepted_audience: ${GYLDIG_SERVICE_BRUKER}
  issuer.azuread:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
    accepted_audience: ${AZURE_APP_CLIENT_ID}
    proxyurl: http://webproxy-nais.nav.no:8088
    cookie_name: azure_token

STS_DISCOVERY_URL: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
