name: Build-Deploy-Prod
on:
  push:
    branches:
      - 'main'

permissions:
  contents: "read"
  id-token: "write"

jobs:
  build:
    name: Build, push and deploy to prod-fss
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Bygg med Maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B --no-transfer-progress package --settings .m2/maven-settings.xml --file pom.xml
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: teamfamilie
          byosbom: target/classes/META-INF/sbom/application.cdx.json
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
  deploy:
    name: Deploy to FSS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: app-prod.yaml
          IMAGE: ${{ needs.build.outputs.image }}