name: Deploy-Master-Dev
on:
  workflow_dispatch:
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/familie-ef-infotrygd-feed:latest
jobs:
  deploy-to-dev:
    name: Deploy master til dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Deploy til dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: app-preprod.yaml