name: Deploy-Main-Dev
on:
  workflow_dispatch:
env:
  IMAGE: ghcr.io/navikt/familie-ef-infotrygd-feed:latest
jobs:
  deploy-to-dev:
    name: Deploy main til dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy til dev-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: app-preprod.yaml